---
apiVersion: v1
kind: Namespace
metadata:
  name: etherpad
---
apiVersion: v1
kind: Secret
metadata:
  name: acm-app-secret
  namespace: etherpad
data:
  accessToken: YmM2M2JhNTFhOWI5MWY4N2ExMGY5ZmEzMGQ4Mzg1MzNmMzhkOGY5YQ==
  user: YXZhbGVyb3I=
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: toweraccess
  namespace: etherpad
data:
  host: YW5zaWJsZS10b3dlci13ZWItc3ZjLXRvd2VyLmFwcHMuY2x1c3Rlci05YTU2LjlhNTYuZXhhbXBsZS5vcGVudGxjLmNvbQ==
  token: QTF0Tmh4aU5CelZVdlB2aXliclV1eUNUbFNFWFZl
type: Opaque

