---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: deployment-notification
  namespace: etherpad
  labels:
    app.kubernetes.io/name: etherpad
spec:
  tower_auth_secret: toweraccess
  job_template_name: telegram-app-notification
  extra_vars:
    #CLUSTER: baremetal-uk
    APPLICATION: Etherpad
