# This is for the local ARGO on the Hub
---
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: argo-acm-clusters
  namespace: openshift-gitops
spec:
  argoServer:
    cluster: local-cluster
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1alpha1
    name: local-cluster
    namespace: openshift-gitops

# This is the ManagedClusterSetBinding to the openshift-gitops namespace
---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: ManagedClusterSetBinding
metadata:
  name: aws-clusters
  namespace: openshift-gitops
spec:
  clusterSet: aws-clusters

#This is the placement resource for targeting Managed Clusters for
---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: local-cluster
  namespace: openshift-gitops
spec:
  clusterSets:
  - aws-clusters
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          vendor: OpenShift
