---
- name: Telegram messaging
  hosts: localhost
  vars_files: 
    - telegram_vars.yml
  collections: 
    - community.general
  tasks:
    - name: Send message
    telegram:
      token: "{{ tokenBot }}"
      api_args:
        chat_id: "{{ chatID }}"
        parse_mode: "markdown"
        text: 'The application "{{ APPLICATION }}" has been deployed to cluster "{{ item }}"'
        disable_web_page_preview: True
        disable_notification: True
  
