---
- name: Telegram messaging
  hosts: localhost

  collections:
    - community.general
  tasks:
    - name: telegram_msg
      telegram:
        token:  '1957180056:AAGpI5tz9uUJEjbffss8TfOWuhuJMg8ZBNc'
        chat_id: -520706713
        msg: 'whateves'
