---
- name: Telegram messaging
  hosts: localhost
  vars_files: 
    - telegram_vars.yml
  collections: 
    - community.general
  tasks:
    - name: Send message
      telegram:
        token: "{{ tokenBot }}"
        chat_id: "{{ chatID }}"
        #msg_format: "markdown"
        msg: 'The test has been successful'
  
