---
- name: Telegram messaging
  hosts: localhost
  vars_files: 
    - telegram_vars.yml
  collections: 
    - community.general
  tasks:
    - name: Send message
    telegram:
      token: 'bot1957180056:AAGpI5tz9uUJEjbffss8TfOWuhuJMg8ZBNc'
      api_args:
        chat_id: '-520706713'
        parse_mode: "markdown"
        text: 'The test has been successful'
        disable_web_page_preview: True
        disable_notification: True
  
