---
apiVersion: v1
kind: Namespace
metadata:
  name: etherpad
---
apiVersion: v1
kind: Secret
metadata:
  name: acm-app-secret
  namespace: etherpad
data:
  accessToken: YmM2M2JhNTFhOWI5MWY4N2ExMGY5ZmEzMGQ4Mzg1MzNmMzhkOGY5YQ==
  user: YXZhbGVyb3I=
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: toweraccess
  namespace: etherpad
stringData:
  host: https://ansible-tower-web-svc-tower.apps.acmhub.d5f3.sandbox840.opentlc.com
  token: iujbsfN7zsueC70G1u4d8ajReTKD7c
type: Opaque

